### PR TITLE
16 projects description

### PR DESCRIPTION
**Pull request by nroh555**
## Context

Created the projects description page that lists all the projects and their corresponding information from the CMS. Below is a screenshot of what it looks like

![image](https://github.com/UoaWDCC/wdcc-website-v3/assets/100507962/6df793d6-c488-402b-b0dc-54d97abbfab8

## How To Review

Visit http://localhost:4321/projects once you have populate the CMS with some data

### CODE REVIEW

**Review by Oculux314 — CHANGES_REQUESTED** [review]
Ooo this looks cool! Just be aware of some bugs:

- Site breaks when there are no projects
image
- If a Strapi user doesn't upload an image in exactly a small format this error triggers:
image
- Consider truncating text when the title or description overflows
image
- Consider adding the description to the CMS so the 2026 team doesn't have to come read all our messy code 😁
- I recommend modifying global.css not editing header styles raw in the HTML since these styles are reused across the project
image
- Remember to use the tailwind.config custom colors!
image
- And don't forget to `yarn lint`!

Love the modularisation, thought for extra requirements later on (e.g. multiple demos) and responsiveness of the page!

Okay sorry for the spam ik it's a lot of nits but it'll make the website better and more resistant to possible issues from a team that hasn't worked on this project! P.s. did you still want me to help style the project card?

**Review by chrisv09 — COMMENTED** [review]
Looks good

**Review by TrissyG — APPROVED** [review]
Only 2 gripes are that there seems to be **lack of styling configurability for Projects-Description using the <MarkdownComponent>** (or any default styles applied when the .md is parsed into corresponding HTML tags?)
image
Responsiveness on the card is mostly good but the **technologies hide behind the button:**
image

Rest of the PR contents LGTM so happy to merge and hotfix (open a bug issue) due to dependencies

**Review by Oculux314 — APPROVED** [review]
Thanks Chris! It looks fabulous 💚 

I added a commit which is just a lint btw

**Pull request merged**
