### PR TITLE
#3: [Home] hero

### PR DESCRIPTION
**Pull request by raymondyangdev**
## Context

The hero section is a crucial part of the homepage, designed to grab the users attention and encourage them to explore more about WDCC. This update implements an engaging call-to-action on the landing page

Closes [#3: [Home] hero](https://github.com/UoaWDCC/wdcc-website-v3/issues/6)

## What Changed?

- Added a new Hero section to the homepage.
- Incorporated an call-to-action button with a join link.

## How To Review

1. web/src/components/home/Hero.tsx
2. web/src/pages/index.astro

## Testing

- Manually tested the Hero section appearance and responsiveness across screen sizes.
- Verified the call-to-action button's link redirects to Google form.
- No significant risks identified, changes are confined to the homepage.

## Notes
Nil

### CODE REVIEW

**Review by Oculux314 — COMMENTED** [review]
:D omg stellar

3 suggestions:
- When the screen gets to phone size the line height makes the title look weird - maybe consider reducing the line height?
image
- Since this is the first content PR, I bet many people are gonna want to use those buttons and image (it's responsive) - do you think they warrant their own components?
- Would recommend defining a new tailwind color in `tailwind.config.mjs` rather than using `style`.
image

**Comment by raymondyangdev** [comment]
@Oculux314 

Thanks Nate for picking those up. I only tested as small as my browser could get 😆 but I've fixed it tested it at different sizes using the Dev Tools.

I agree that the `Pill Button` and `Responsive Image` should have their own components due to their customised styling and functionality.

However, I don't think the `Join for 2024` button needs its own component. Since it's just a straightforward implementation using a Shadcn Button, we can use the Button component directly without nesting it in a separate component.

**Review by Bobsters6666 — APPROVED** [review]
Looks good!! 🔥

Just made some tiny styling changes
- Increased text size for <md screens to 4xl, added an extra text size breakpoint lg>x>md
- Increased gap between flex children in <lg screens

**Comment by raymondyangdev** [comment]
After some more thought, `SkybluePillButton` also seems redundant, given that we only need to specify rounded-full to `className` to turn it into a Pill Button and the `skyblue` variant has been added to `web/src/components/ui/button.tsx`.

**Review by Oculux314 — APPROVED** [review]
I haven't been able to test the new changes cause for some reason Strapi's really not liking my frontend. But the code looks good and I agree with the button decisions, so approving!

**Pull request merged**
